### ISSUE TITLE
Make `AdminState` in `InitializeStates` optional

### ISSUE THREAD

**Issue by U-lis** [planetarium/lib9c#1287]
In NineChronicles Headless, we have to provide admin address to create genesis block.
This `Admin` address is useful in several situations, but I think this required admin address raises hurdle to make local genesis block and start new network.

So I suggest to make `AdminState` optional in `InitializeStates` method. This will make admin-less blockchain network, but that is no big deal for local network.

I'm not sure how much works to achieve this, so please comment what you think about before I start.

**Comment by moreal** [comment]
This comment is a record to research the `InitializeStates` and to plan how to make the `AdminState` parameter optional safely.

### Current state

At the current [HEAD](https://github.com/planetarium/lib9c/commit/4262b596e2d02f1eda8fc109f2c66bddd6518736), the `InitializeStates` receives `AdminState adminAddressState` but the `InitializeStates.AdminAddress` variable has a default value, `Bencodex.Types.Dictionary.Empty` and the default value is wrong because `AdminState` requires `Bencodex.Types.Dictionary` including `address`, `admin_address`, `valid_until` fields.

https://github.com/planetarium/lib9c/blob/9fa307cd4cd9fbd4496ee50c714b703c380184c9/Lib9c/Model/State/AdminState.cs#L24-L28

Luckily, there is only one `initialize_states` transaction in Nine Chronicles Mainnet according to [9cscan](https://9cscan.com/transactions?action=initialize_states) 😮 . 

### To update actions safely...

To update `InitializeStates` safely, it should have serialized action and its action evaluation result. The first one will be used to check serialization (`IAction.LoadPlainValue`, `IAction.PlainValue`) and the second one will be used to check execution (`IAction.Execute`). To test such things easily, I tried to introduce *Snapshot Testing* in #1200 but it is stuck now.

### PLAN?

For implementation:

1. Correct incorrect default value of `AdminAddress` property.
1. Make `AdminAddress` property nullable and make constructor parameter nullable also.
1. If the `AdminAddress` is not `null`, add the `admin_address_state` pair. Else do nothing.
1. In the `InitializeStates.LoadPlainValue`, if the `admin_address_state` key exists, get
1. If the `AdminAddress` is not `null`, set `AdminAddress` state to the `Addresses.AdminState`(?). (The current behavior)

For test:

1. Add test to check serialization with the action in the genesis block.
1. Add testcase to check setting `AdminState` optionally. If it gives `adminAddressState` parameter as `null`, the state at  `Addresses.AdminState` should be `null`.
